- name: "Upgrade packages."
  become: true
  apt:
    upgrade: "yes"
    
- name: "Install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

# - name: "Making dir"
#   file:
#     path: ~/backend-app
#     state: directory

- name: "Extracting app"
  unarchive:
    src: artifact.tar.gz
    dest: ~/

# - name: "installing dependencies"
#   shell: |
#     cd ~/backend-app
#     npm i

- name: "Starting app"
  shell: |
    #cd ~/backend-app/dist
    npm install
    pm2 stop default
    pm2 start npm -- start