- name: "Upgrade packages."
  become: true
  apt:
    upgrade: "yes"
    
- name: "Install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "Making dir"
  file:
    path: ~/backend-app
    state: directory

- name: "Extracting app"
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend-app

- name: "installing dependencies"
  shell: |
    cd ~/backend-app
    npm i

- name: "Starting app"
  shell: |
    cd ~/backend-app/dist
    pm2 stop default
    pm2 start main.js