- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"
    
- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Extract artifact
  become: true
  unarchive:
    src: project/artifact.tar.gz
    dest: ~/

- name: Starting app
  become: true
  command: |
    cd dist
    pm2 stop default
    pm2 start main.js