- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"
    
- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "mkdir dir"
  file:
    path: ~/Backend-Application
    state: directory

- name: "Unarchive tar"
  unarchive:
    src: artifact.tar.gz
    dest: ~/Backend-Application

- name: "installing dependencies"
  shell: |
    cd ~/Backend-Application
    npm i

- name: "run with PM2"
  shell: |
    cd ~/Backend-Application/dist
    pm2 stop default
    pm2 start main.js