pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Frontend') {
            def frontendCacheDir = "${WORKSPACE}/frontend-cache"

            steps {
                sh '''
                    cd frontend/
                    npm install
                    npm run build
                '''
                archiveArtifacts artifacts: 'dist/**', allowEmptyArchive: true
                stash name: 'frontend-cache', includes: frontendCacheDir


            }
        }

        stage('Build Backend'){
            def backendCacheDir = "${WORKSPACE}/backend-cache"

            steps{
                sh '''
                    cd backend/
                    npm install
                    npm run build 
                '''
                archiveArtifacts artifacts: 'dist/**', allowEmptyArchive: true
                stash name: 'backend-cache', includes: backendCacheDir
            }
        }
    }
}
