@Library('my-shared-lib-jenkins') _
pipeline {
    agent any

    environment{
        TYPEORM_CONNECTION='postgres'
        TYPEORM_ENTITIES='./dist/modules/domain/*/.entity{.ts,.js}'
        TYPEORM_HOST='postgres'
        TYPEORM_PORT='5432'
        TYPEORM_USERNAME='postgres'
        TYPEORM_PASSWORD='postgresPass'
        TYPEORM_DATABASE='postgres'
        TYPEORM_MIGRATIONS='./dist/migrations/.*ts'
        TYPEORM_MIGRATIONS_DIR='./dist/migrations'
        NODE_ENV='production' 
        VERSION='1'
    }

    tools {
        // Define the Node.js tool by the name you provided in the tool configuration.
        
        nodejs "Node"
    }


    stages {
        stage('echo node version') {
            steps {
                node (label: 'any') {
                    sh "node --version"
                }

            }
        }
       
    } 

       /*  post {
            failure {
                echo 'Pipeline failed'
                gcpCleanUp()
                revetMigrations()
            }
    }*/
}